-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.associates
(
    associate_id integer NOT NULL DEFAULT nextval('associates_id_seq'::regclass),
    account character varying(255) COLLATE pg_catalog."default" NOT NULL,
    location character varying(255) COLLATE pg_catalog."default",
    parent_ou character varying(255) COLLATE pg_catalog."default",
    business_group character varying(255) COLLATE pg_catalog."default" DEFAULT 'Digital Operations'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT associates_pkey PRIMARY KEY (associate_id)
);

CREATE TABLE IF NOT EXISTS public.idea_team
(
    id serial NOT NULL,
    idea_id integer NOT NULL,
    associate_id integer NOT NULL,
    is_primary boolean DEFAULT false,
    role character varying(128) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    business_group character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT idea_team_pkey PRIMARY KEY (id),
    CONSTRAINT idea_team_idea_id_associate_id_key UNIQUE (idea_id, associate_id)
);

CREATE TABLE IF NOT EXISTS public.ideas
(
    idea_id serial NOT NULL,
    submitter_id integer,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    summary text COLLATE pg_catalog."default",
    challenge_opportunity character varying(255) COLLATE pg_catalog."default",
    scalability character varying(50) COLLATE pg_catalog."default",
    novelty character varying(50) COLLATE pg_catalog."default",
    benefits text COLLATE pg_catalog."default",
    risks text COLLATE pg_catalog."default",
    responsible_ai character varying(255) COLLATE pg_catalog."default",
    additional_info text COLLATE pg_catalog."default",
    prototype_url character varying(255) COLLATE pg_catalog."default",
    timeline character varying(50) COLLATE pg_catalog."default",
    success_metrics text COLLATE pg_catalog."default",
    expected_outcomes text COLLATE pg_catalog."default",
    scalability_potential character varying(50) COLLATE pg_catalog."default",
    business_model text COLLATE pg_catalog."default",
    competitive_analysis text COLLATE pg_catalog."default",
    risk_mitigation text COLLATE pg_catalog."default",
    second_file_url character varying(255) COLLATE pg_catalog."default",
    participation_week character varying(50) COLLATE pg_catalog."default",
    build_phase character varying(50) COLLATE pg_catalog."default",
    build_preference character varying(50) COLLATE pg_catalog."default",
    code_preference character varying(50) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    business_group character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT ideas_pkey PRIMARY KEY (idea_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    emp_id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role character varying(64) COLLATE pg_catalog."default" DEFAULT 'user'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_emp_id_key UNIQUE (emp_id)
);

ALTER TABLE IF EXISTS public.idea_team
    ADD CONSTRAINT idea_team_associate_id_fkey FOREIGN KEY (associate_id)
    REFERENCES public.associates (associate_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.idea_team
    ADD CONSTRAINT idea_team_idea_id_fkey FOREIGN KEY (idea_id)
    REFERENCES public.ideas (idea_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ideas
    ADD CONSTRAINT fk_submitter FOREIGN KEY (submitter_id)
    REFERENCES public.associates (associate_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_idea_associate_id
    ON public.ideas(submitter_id);


ALTER TABLE IF EXISTS public.ideas
    ADD CONSTRAINT ideas_associate_id_fkey FOREIGN KEY (submitter_id)
    REFERENCES public.associates (associate_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_idea_associate_id
    ON public.ideas(submitter_id);

END;